name: Deploy backend to Azure

on:
  workflow_run:
    workflows: ["Publish Package"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  AZURE_WEBAPP_NAME: janvhanssen-backend
  OWNER: JanVHanssen
  REPO: SoftwareEngineering
  GROUP_ID: be.ucll.se
  ARTIFACT_ID: janvhanssen-backend
  VERSION: 0.0.1-SNAPSHOT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "21"

      - name: Configure Maven credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>github</username>
                <password>\${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Download JAR from GitHub Packages
        run: |
          mvn -B dependency:get \
            -Dartifact=${GROUP_ID}:${ARTIFACT_ID}:${VERSION}:jar \
            -DrepoUrl=https://maven.pkg.github.com/${OWNER}/${REPO}

          # GROUP_ID met punten → mapstructuur
          GROUP_PATH=$(echo $GROUP_ID | tr '.' '/')
          cp ~/.m2/repository/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}/${ARTIFACT_ID}-${VERSION}.jar app.jar

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.jar
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CD57E2473E7D4D119249C4C5D90C1BA1 }}
