name: Direct Deploy from Source

on:
  workflow_run:
    workflows: ["Publish Package"]
    types: [completed]

  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  AZURE_WEBAPP_NAME: janvhanssen-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: Configure Maven credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>x-access-token</username>
                <password>${{ secrets.PAT_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Download JAR from GitHub Packages
        run: |
          mvn -X -e dependency:get \
            -Dartifact=be.ucll.se:janvhanssen-backend:0.0.1-SNAPSHOT:jar \
            -DrepoUrl=https://maven.pkg.github.com/UCLL-AO-SoftwareEngineering/backend-2425-JanVHanssen
          cp ~/.m2/repository/be/ucll/se/janvhanssen-backend/0.0.1-SNAPSHOT/janvhanssen-backend-0.0.1-SNAPSHOT.jar app.jar

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.jar
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CD57E2473E7D4D119249C4C5D90C1BA1 }}
