name: Publish Package

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  PROJECT_DIR: backend-2425-JanVHanssen/janvhanssen-backend
  MAVEN_SETTINGS: ~/.m2/settings.xml

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "21"

      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ${{ env.MAVEN_SETTINGS }} <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>github</username>
                <password>\${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build & publish to GitHub Packages
        working-directory: ${{ env.PROJECT_DIR }}
        run: mvn -B -s ${{ env.MAVEN_SETTINGS }} -DskipTests clean deploy
