name: Publish Package

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if PAT_TOKEN is set
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "❌ PAT_TOKEN is NOT set"
            exit 1
          else
            echo "✅ PAT_TOKEN is set"
          fi

      - name: Configure Maven credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>x-access-token</username>
                <password>${{ secrets.PAT_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: Build and Publish to GitHub Packages
        run: mvn -s ~/.m2/settings.xml -X -e -DskipTests clean deploy
        working-directory: ./janvhanssen-backend

        # test
