<<<<<<< HEAD
name: Deploy backend to Azure

on:
  workflow_run:
    workflows: ["Publish Package"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  AZURE_WEBAPP_NAME: janvhanssen-backend
  OWNER: JanVHanssen
  REPO: SoftwareEngineering
  GROUP_ID: be.ucll.se
  ARTIFACT_ID: janvhanssen-backend
  VERSION: 0.0.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "21"

      - name: Configure Maven credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>github</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Download JAR from GitHub Packages
        run: |
          echo "Attempting to download artifact: ${GROUP_ID}:${ARTIFACT_ID}:${VERSION}"
          mvn -X -B dependency:get \
            -Dartifact=${GROUP_ID}:${ARTIFACT_ID}:${VERSION}:jar \
            -DrepositoryId=github \
            -DrepoUrl=https://maven.pkg.github.com/${OWNER}/${REPO}

          GROUP_PATH=$(echo $GROUP_ID | tr '.' '/')
          echo "Checking if artifact was downloaded:"
          ls -lR ~/.m2/repository/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}/

          cp ~/.m2/repository/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}/*.jar app.jar
          ls -l app.jar

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.jar
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CD57E2473E7D4D119249C4C5D90C1BA1 }}
=======
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - janvhanssen-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'janvhanssen-backend'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A71A30C92B524AF0B05339A5F74302FB }}
>>>>>>> 9f7479372cf138ae46346e7a3a75ebd97b6900b9
