name: Deploy backend to Azure

on:
  workflow_run:
    workflows: ["Publish Package"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  actions: read

env:
  AZURE_WEBAPP_NAME: janvhanssen-backend
  OWNER: JanVHanssen
  REPO: SoftwareEngineering
  GROUP_ID: be.ucll.se
  ARTIFACT_ID: janvhanssen-backend
  VERSION: 0.0.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }} # 🔴 PAT gebruiken voor checkout

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "21"
          server-id: github
          server-username: github
          server-password: ${{ secrets.PAT_TOKEN }} # 🔴 PAT gebruiken voor Maven auth

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>github</username>
                <password>${{ secrets.PAT_TOKEN }}</password>  # 🔴 PAT gebruiken hier
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/${{ env.OWNER }}/${{ env.REPO }}</url>
                    <releases>
                      <enabled>true</enabled>
                    </releases>
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Download JAR from GitHub Packages
        run: |
          echo "Attempting to download artifact from GitHub Packages"
          mvn -X -B org.apache.maven.plugins:maven-dependency-plugin:3.7.0:get \
            -DremoteRepositories=github::::https://maven.pkg.github.com/${{ env.OWNER }}/${{ env.REPO }} \
            -Dartifact=${{ env.GROUP_ID }}:${{ env.ARTIFACT_ID }}:${{ env.VERSION }}:jar

          GROUP_PATH=$(echo ${{ env.GROUP_ID }} | tr '.' '/')
          echo "Downloaded files:"
          ls -l ~/.m2/repository/$GROUP_PATH/${{ env.ARTIFACT_ID }}/${{ env.VERSION }}/

          cp ~/.m2/repository/$GROUP_PATH/${{ env.ARTIFACT_ID }}/${{ env.VERSION }}/*.jar app.jar
          echo "JAR file ready for deployment:"
          ls -l app.jar

      - name: Azure Login with Publish Profile
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CD57E2473E7D4D119249C4C5D90C1BA1 }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.jar
