name: Publish Package

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  PROJECT_DIR: backend-2425-JanVHanssen/janvhanssen-backend
  MAVEN_SETTINGS: ~/.m2/settings.xml

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # ---------------- Checkout ----------------
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # géén 'path:' meer

      # ---------------- Controleer structuur ----------------
      - name: Verify directory structure
        run: |
          ls -R
          ls -la ${{ env.PROJECT_DIR }}/pom.xml || echo "POM not found!"

      # ---------------- Java & Maven ----------------
      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "21"
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Maven
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          mkdir -p ~/.m2
          cat > ${{ env.MAVEN_SETTINGS }} <<'EOF'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
          <server>
          <id>github</id>
          <username>${{ github.actor }}</username>
          <password>${{ secrets.GITHUB_TOKEN }}</password>
          </server>
          </servers>
          <profiles>
          <profile>
          <id>github</id>
          <repositories>
          <repository>
          <id>github</id>
          <url>https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
          </repository>
          </repositories>
          </profile>
          </profiles>
          <activeProfiles>
          <activeProfile>github</activeProfile>
          </activeProfiles>
          </settings>
          EOF
      - name: Test GitHub Packages access
        run: |
          curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }} -Iv

      # ---------------- Versie bumpen ----------------
      - name: Set unique version
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION="${BASE_VERSION%.*}-$(date +%s)"
          mvn versions:set -DnewVersion=$NEW_VERSION
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # ---------------- Build & Deploy ----------------
      - name: Build and publish
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          mvn -B -s ${{ env.MAVEN_SETTINGS }} -DskipTests clean deploy

      - name: Verify published package
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/users/${{ github.repository_owner }}/packages/maven/${{ env.ARTIFACT_ID }}/versions \
            | jq .
