name: Publish Package

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_DIR: backend-2425-JanVHanssen/janvhanssen-backend # 🔴 Pas dit aan naar jouw pad
  MAVEN_SETTINGS: ~/.m2/settings.xml

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          path: src # 🔴 Checkout in een subdirectory

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "21"
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.PAT_TOKEN }}

      - name: Configure Maven
        working-directory: ${{ env.PROJECT_DIR }} # 🔴 Werk in de juiste directory
        run: |
          mkdir -p ~/.m2
          cat > ${{ env.MAVEN_SETTINGS }} <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.PAT_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Determine version
        id: version
        working-directory: ${{ env.PROJECT_DIR }} # 🔴 Werk in de juiste directory
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=${BASE_VERSION}" >> $GITHUB_OUTPUT

      - name: Build and publish
        working-directory: ${{ env.PROJECT_DIR }} # 🔴 Werk in de juiste directory
        run: |
          mvn -B -s ${{ env.MAVEN_SETTINGS }} -DskipTests clean deploy
