name: Publish Package

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  PROJECT_DIR: backend-2425-JanVHanssen/janvhanssen-backend
  MAVEN_SETTINGS: ~/.m2/settings.xml

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: |
          BASE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "version=${BASE_VERSION}-$(date +%s)" >> $GITHUB_OUTPUT
          else
            echo "version=${BASE_VERSION}-SNAPSHOT" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: "21"
          server-id: github
          server-username: github
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Maven
        run: |
          mkdir -p ~/.m2
          cat > ${{ env.MAVEN_SETTINGS }} <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>github</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build & publish
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Update version if snapshot
          if [[ "${{ steps.version.outputs.version }}" == *"-SNAPSHOT"* ]]; then
            mvn versions:set -DnewVersion=${{ steps.version.outputs.version }}
          fi

          mvn -B -s ${{ env.MAVEN_SETTINGS }} -DskipTests clean deploy
